### PR TITLE
Dropped Type suffix to match slonik@>=27

### PR DESCRIPTION
**Pull request by danielgormly**
Hi Gajus, this is just to match the changes in Slonik@27. The build fails because of the type changes in the current version. You may want to check the versioning I used, I may not be thinking about the effects as extensively as you. Thank you for the excellent library.

### CODE REVIEW

**Comment by ripecosta** [comment]
@gajus Any chance this PR can be looked at again? Right now it requires bypassing type safety for the plugin to work with the latest version of Slonik. Thanks!

**Comment by gajus** [comment]
No clue why Travis builds are failing. Looks like there were some breaking changes to Travis manifests.

**Comment by ripecosta** [comment]
Have you tried `dist: focal` rather than bionic?

**Comment by ripecosta** [comment]
@gajus Fixed it in:
- #11

**Pull request merged**
